env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - simple-import-sort
  - unused-imports
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "off"
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: "^_"
      args: after-used
      argsIgnorePattern: "^_"
